//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bimangle.ForgeEngine.Dgn {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bimangle.ForgeEngine.Dgn.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The Entire Model 的本地化字符串。
        /// </summary>
        internal static string ContentTypeBasic {
            get {
                return ResourceManager.GetString("ContentTypeBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Entire Model - LOD(Slow) 的本地化字符串。
        /// </summary>
        internal static string ContentTypeBasicLod {
            get {
                return ResourceManager.GetString("ContentTypeBasicLod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shell Only - By Element (Slow) 的本地化字符串。
        /// </summary>
        internal static string ContentTypeShellOnlyByElement {
            get {
                return ResourceManager.GetString("ContentTypeShellOnlyByElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shell Only - By Mesh (Very Slow) 的本地化字符串。
        /// </summary>
        internal static string ContentTypeShellOnlyByMesh {
            get {
                return ResourceManager.GetString("ContentTypeShellOnlyByMesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Files|*.* 的本地化字符串。
        /// </summary>
        internal static string DialogFilterAllFile {
            get {
                return ResourceManager.GetString("DialogFilterAllFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 License File|*.lic 的本地化字符串。
        /// </summary>
        internal static string DialogFilterLicenseFile {
            get {
                return ResourceManager.GetString("DialogFilterLicenseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WebGL Model|*.svfzip 的本地化字符串。
        /// </summary>
        internal static string DialogFilterSvfzip {
            get {
                return ResourceManager.GetString("DialogFilterSvfzip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load license file 的本地化字符串。
        /// </summary>
        internal static string DialogTitleLoadLicense {
            get {
                return ResourceManager.GetString("DialogTitleLoadLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse target file 的本地化字符串。
        /// </summary>
        internal static string DialogTitleSelectTarget {
            get {
                return ResourceManager.GetString("DialogTitleSelectTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A problem with current Revit instance support for export was detected, possibly because the material library was not installed correctly. This operation may not be successful. Are you sure you want to continue? 的本地化字符串。
        /// </summary>
        internal static string ExportWillFailBecauseMaterialLib {
            get {
                return ResourceManager.GetString("ExportWillFailBecauseMaterialLib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Optimization glTF node hierarchy and reduce data size.  的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionAllowRegroupNodes {
            get {
                return ResourceManager.GetString("FeatureDescriptionAllowRegroupNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatic Align Origin To Site Plane Center 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionAutoAlignOriginToSiteCenter {
            get {
                return ResourceManager.GetString("FeatureDescriptionAutoAlignOriginToSiteCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatic Fit Viewport 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionAutoViewport {
            get {
                return ResourceManager.GetString("FeatureDescriptionAutoViewport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Consolidate assembly&apos;s members to one node  的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionConsolidateAssembly {
            get {
                return ResourceManager.GetString("FeatureDescriptionConsolidateAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Consolidate Composite Element, such as Railing/Stairs/CurtainWall/StackedWall/NestedFamily.  的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionConsolidateCompositeElement {
            get {
                return ResourceManager.GetString("FeatureDescriptionConsolidateCompositeElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Consolidate model group&apos;s members to one node 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionConsolidateGroup {
            get {
                return ResourceManager.GetString("FeatureDescriptionConsolidateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Consolidate each link instance to one node 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionConsolidateLinkInstance {
            get {
                return ResourceManager.GetString("FeatureDescriptionConsolidateLinkInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically split the whole model into small parts to improve the loading speed.  的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionEnableAutomaticSplit {
            get {
                return ResourceManager.GetString("FeatureDescriptionEnableAutomaticSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate Primitive Outline for Cesium 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionEnableCesiumPrimitiveOutline {
            get {
                return ResourceManager.GetString("FeatureDescriptionEnableCesiumPrimitiveOutline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Embed Georeferencing To Tileset 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionEnableEmbedGeoreferencing {
            get {
                return ResourceManager.GetString("FeatureDescriptionEnableEmbedGeoreferencing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Quantized Attributes 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionEnableQuantizedAttributes {
            get {
                return ResourceManager.GetString("FeatureDescriptionEnableQuantizedAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Texture WebP (Cesium &gt;= v1.54) 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionEnableTextureWebP {
            get {
                return ResourceManager.GetString("FeatureDescriptionEnableTextureWebP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Unlit Materials, Mean no shadows, no highlights, just plain. 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionEnableUnlitMaterials {
            get {
                return ResourceManager.GetString("FeatureDescriptionEnableUnlitMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionExcludeLines {
            get {
                return ResourceManager.GetString("FeatureDescriptionExcludeLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionExcludePoints {
            get {
                return ResourceManager.GetString("FeatureDescriptionExcludePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionExcludeProperties {
            get {
                return ResourceManager.GetString("FeatureDescriptionExcludeProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionExcludeTexture {
            get {
                return ResourceManager.GetString("FeatureDescriptionExcludeTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export all 2d view 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionExport2DViewAll {
            get {
                return ResourceManager.GetString("FeatureDescriptionExport2DViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 2d view of drawing sheet 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionExport2DViewOnlySheet {
            get {
                return ResourceManager.GetString("FeatureDescriptionExport2DViewOnlySheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Construction Class Element 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionExportElementClassConstruction {
            get {
                return ResourceManager.GetString("FeatureDescriptionExportElementClassConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Dimension Class Element 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionExportElementClassDimension {
            get {
                return ResourceManager.GetString("FeatureDescriptionExportElementClassDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export grids to green line 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionExportGrids {
            get {
                return ResourceManager.GetString("FeatureDescriptionExportGrids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export ModelItem&apos;s hyperlink 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionExportHyperlink {
            get {
                return ResourceManager.GetString("FeatureDescriptionExportHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export openings to transparent solid 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionExportOpenings {
            get {
                return ResourceManager.GetString("FeatureDescriptionExportOpenings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export rooms to transparent solid 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionExportRooms {
            get {
                return ResourceManager.GetString("FeatureDescriptionExportRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Svfzip Model 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionExportSvfzip {
            get {
                return ResourceManager.GetString("FeatureDescriptionExportSvfzip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extract Building&apos;s Shell (Slow) 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionExtractShell {
            get {
                return ResourceManager.GetString("FeatureDescriptionExtractShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Force 2D view display style to wireframe mode before export, avoid output raster images that cannot be selected. 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionForce2DViewUseWireframe {
            get {
                return ResourceManager.GetString("FeatureDescriptionForce2DViewUseWireframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The output data is compatible with EarthSDK 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionForEarthSdk {
            get {
                return ResourceManager.GetString("FeatureDescriptionForEarthSdk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate Dwg Drawing file for 2d view 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionGenerateDwgDrawing {
            get {
                return ResourceManager.GetString("FeatureDescriptionGenerateDwgDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filename: elements_[data|props].json 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionGenerateElementData {
            get {
                return ResourceManager.GetString("FeatureDescriptionGenerateElementData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate Leaflet Tile set for 2d view (Minimum 2G memory required) 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionGenerateLeaflet {
            get {
                return ResourceManager.GetString("FeatureDescriptionGenerateLeaflet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate model properties database file (SQLite) 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionGenerateModelsDb {
            get {
                return ResourceManager.GetString("FeatureDescriptionGenerateModelsDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate 400x400,200x200,100x100 thumbnail image (thumb{nnn}.png) 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionGenerateThumbnail {
            get {
                return ResourceManager.GetString("FeatureDescriptionGenerateThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gray Mode 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionGray {
            get {
                return ResourceManager.GetString("FeatureDescriptionGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionOnlySelected {
            get {
                return ResourceManager.GetString("FeatureDescriptionOnlySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Optimize the geometry surface material, and intelligently adjust the geometry surface for double-sided material to single-sided material output, reducing flicker problems 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionOptimizationFaceMaterial {
            get {
                return ResourceManager.GetString("FeatureDescriptionOptimizationFaceMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Reduce Geometry Node To Parent Node 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionReduceGeometryNode {
            get {
                return ResourceManager.GetString("FeatureDescriptionReduceGeometryNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Regroup Elements By Links. 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionRegroupForLink {
            get {
                return ResourceManager.GetString("FeatureDescriptionRegroupForLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Regroup Elements By Link file folder hierarchy. 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionRegroupForLinkFolderHierarchy {
            get {
                return ResourceManager.GetString("FeatureDescriptionRegroupForLinkFolderHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Regroup Elements By WorkSet.  的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionRegroupForWorkSet {
            get {
                return ResourceManager.GetString("FeatureDescriptionRegroupForWorkSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Publish data using 3D Tiles 1.1 specification 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionUse3DTilesSpecification11 {
            get {
                return ResourceManager.GetString("FeatureDescriptionUse3DTilesSpecification11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use level category by element&apos;s bounding box 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionUseBoundLevelCategory {
            get {
                return ResourceManager.GetString("FeatureDescriptionUseBoundLevelCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use current 3d view camera viewport 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionUseCurrentViewport {
            get {
                return ResourceManager.GetString("FeatureDescriptionUseCurrentViewport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compress Mesh By Google Draco (Slow) 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionUseGoogleDraco {
            get {
                return ResourceManager.GetString("FeatureDescriptionUseGoogleDraco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionUseLevelCategory {
            get {
                return ResourceManager.GetString("FeatureDescriptionUseLevelCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use level category like Navisworks 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionUseNwLevelCategory {
            get {
                return ResourceManager.GetString("FeatureDescriptionUseNwLevelCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use current view&apos;s override graphic color 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionUseViewOverrideGraphic {
            get {
                return ResourceManager.GetString("FeatureDescriptionUseViewOverrideGraphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wireframe Mode 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionWireframe {
            get {
                return ResourceManager.GetString("FeatureDescriptionWireframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Optimization glTF node hierarchy 的本地化字符串。
        /// </summary>
        internal static string FeatureNameAllowRegroupNodes {
            get {
                return ResourceManager.GetString("FeatureNameAllowRegroupNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align Origin To Site Plane Center 的本地化字符串。
        /// </summary>
        internal static string FeatureNameAutoAlignOriginToSiteCenter {
            get {
                return ResourceManager.GetString("FeatureNameAutoAlignOriginToSiteCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatic Fit Viewport 的本地化字符串。
        /// </summary>
        internal static string FeatureNameAutoViewport {
            get {
                return ResourceManager.GetString("FeatureNameAutoViewport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Consolidate assembly 的本地化字符串。
        /// </summary>
        internal static string FeatureNameConsolidateAssembly {
            get {
                return ResourceManager.GetString("FeatureNameConsolidateAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Consolidate Composite Element 的本地化字符串。
        /// </summary>
        internal static string FeatureNameConsolidateCompositeElement {
            get {
                return ResourceManager.GetString("FeatureNameConsolidateCompositeElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Consolidate model group 的本地化字符串。
        /// </summary>
        internal static string FeatureNameConsolidateGroup {
            get {
                return ResourceManager.GetString("FeatureNameConsolidateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically Split To Parts 的本地化字符串。
        /// </summary>
        internal static string FeatureNameEnableAutomaticSplit {
            get {
                return ResourceManager.GetString("FeatureNameEnableAutomaticSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate Primitive Outline 的本地化字符串。
        /// </summary>
        internal static string FeatureNameEnableCesiumPrimitiveOutline {
            get {
                return ResourceManager.GetString("FeatureNameEnableCesiumPrimitiveOutline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Embed Georeferencing 的本地化字符串。
        /// </summary>
        internal static string FeatureNameEnableEmbedGeoreferencing {
            get {
                return ResourceManager.GetString("FeatureNameEnableEmbedGeoreferencing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Quantized Attributes 的本地化字符串。
        /// </summary>
        internal static string FeatureNameEnableQuantizedAttributes {
            get {
                return ResourceManager.GetString("FeatureNameEnableQuantizedAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Texture WebP 的本地化字符串。
        /// </summary>
        internal static string FeatureNameEnableTextureWebP {
            get {
                return ResourceManager.GetString("FeatureNameEnableTextureWebP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Unlit Materials 的本地化字符串。
        /// </summary>
        internal static string FeatureNameEnableUnlitMaterials {
            get {
                return ResourceManager.GetString("FeatureNameEnableUnlitMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exclude geometry lines 的本地化字符串。
        /// </summary>
        internal static string FeatureNameExcludeLines {
            get {
                return ResourceManager.GetString("FeatureNameExcludeLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exclude geometry points 的本地化字符串。
        /// </summary>
        internal static string FeatureNameExcludePoints {
            get {
                return ResourceManager.GetString("FeatureNameExcludePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exclude properties data 的本地化字符串。
        /// </summary>
        internal static string FeatureNameExcludeProperties {
            get {
                return ResourceManager.GetString("FeatureNameExcludeProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exclude material texture images 的本地化字符串。
        /// </summary>
        internal static string FeatureNameExcludeTexture {
            get {
                return ResourceManager.GetString("FeatureNameExcludeTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 2D View (All) 的本地化字符串。
        /// </summary>
        internal static string FeatureNameExport2DViewAll {
            get {
                return ResourceManager.GetString("FeatureNameExport2DViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 2D View (Only Sheet) 的本地化字符串。
        /// </summary>
        internal static string FeatureNameExport2DViewOnlySheet {
            get {
                return ResourceManager.GetString("FeatureNameExport2DViewOnlySheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Construction Class Element 的本地化字符串。
        /// </summary>
        internal static string FeatureNameExportElementClassConstruction {
            get {
                return ResourceManager.GetString("FeatureNameExportElementClassConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Dimension Class Element 的本地化字符串。
        /// </summary>
        internal static string FeatureNameExportElementClassDimension {
            get {
                return ResourceManager.GetString("FeatureNameExportElementClassDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export grids 的本地化字符串。
        /// </summary>
        internal static string FeatureNameExportGrids {
            get {
                return ResourceManager.GetString("FeatureNameExportGrids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export hyperlink 的本地化字符串。
        /// </summary>
        internal static string FeatureNameExportHyperlink {
            get {
                return ResourceManager.GetString("FeatureNameExportHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export openings 的本地化字符串。
        /// </summary>
        internal static string FeatureNameExportOpenings {
            get {
                return ResourceManager.GetString("FeatureNameExportOpenings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export rooms 的本地化字符串。
        /// </summary>
        internal static string FeatureNameExportRooms {
            get {
                return ResourceManager.GetString("FeatureNameExportRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Svfzip Model 的本地化字符串。
        /// </summary>
        internal static string FeatureNameExportSvfzip {
            get {
                return ResourceManager.GetString("FeatureNameExportSvfzip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extract Building&apos;s Shell (Slow) 的本地化字符串。
        /// </summary>
        internal static string FeatureNameExtractShell {
            get {
                return ResourceManager.GetString("FeatureNameExtractShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Force Display Style To Wireframe Mode 的本地化字符串。
        /// </summary>
        internal static string FeatureNameForce2DViewUseWireframe {
            get {
                return ResourceManager.GetString("FeatureNameForce2DViewUseWireframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dwg Drawing File (For 2D View) 的本地化字符串。
        /// </summary>
        internal static string FeatureNameGenerateDwgDrawing {
            get {
                return ResourceManager.GetString("FeatureNameGenerateDwgDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate elements data 的本地化字符串。
        /// </summary>
        internal static string FeatureNameGenerateElementData {
            get {
                return ResourceManager.GetString("FeatureNameGenerateElementData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Leaflet (Tiles For 2D View) 的本地化字符串。
        /// </summary>
        internal static string FeatureNameGenerateLeaflet {
            get {
                return ResourceManager.GetString("FeatureNameGenerateLeaflet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate model.sdb 的本地化字符串。
        /// </summary>
        internal static string FeatureNameGenerateModelsDb {
            get {
                return ResourceManager.GetString("FeatureNameGenerateModelsDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate thumbnail 的本地化字符串。
        /// </summary>
        internal static string FeatureNameGenerateThumbnail {
            get {
                return ResourceManager.GetString("FeatureNameGenerateThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gray Mode 的本地化字符串。
        /// </summary>
        internal static string FeatureNameGray {
            get {
                return ResourceManager.GetString("FeatureNameGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export selected elements only 的本地化字符串。
        /// </summary>
        internal static string FeatureNameOnlySelected {
            get {
                return ResourceManager.GetString("FeatureNameOnlySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Optimization face material 的本地化字符串。
        /// </summary>
        internal static string FeatureNameOptimizationFaceMaterial {
            get {
                return ResourceManager.GetString("FeatureNameOptimizationFaceMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Reduce Geometry Node 的本地化字符串。
        /// </summary>
        internal static string FeatureNameReduceGeometryNode {
            get {
                return ResourceManager.GetString("FeatureNameReduceGeometryNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Regroup By Links 的本地化字符串。
        /// </summary>
        internal static string FeatureNameRegroupForLink {
            get {
                return ResourceManager.GetString("FeatureNameRegroupForLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Regroup By Links By Link File Folder 的本地化字符串。
        /// </summary>
        internal static string FeatureNameRegroupForLinkFolderHierarchy {
            get {
                return ResourceManager.GetString("FeatureNameRegroupForLinkFolderHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Regroup By WorkSet.  的本地化字符串。
        /// </summary>
        internal static string FeatureNameRegroupForWorkSet {
            get {
                return ResourceManager.GetString("FeatureNameRegroupForWorkSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Using 3D Tiles 1.1 的本地化字符串。
        /// </summary>
        internal static string FeatureNameUse3DTilesSpecification11 {
            get {
                return ResourceManager.GetString("FeatureNameUse3DTilesSpecification11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use level(bound) category 的本地化字符串。
        /// </summary>
        internal static string FeatureNameUseBoundLevelCategory {
            get {
                return ResourceManager.GetString("FeatureNameUseBoundLevelCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use current viewport 的本地化字符串。
        /// </summary>
        internal static string FeatureNameUseCurrentViewport {
            get {
                return ResourceManager.GetString("FeatureNameUseCurrentViewport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compress Mesh By Google Draco (Slow) 的本地化字符串。
        /// </summary>
        internal static string FeatureNameUseGoogleDraco {
            get {
                return ResourceManager.GetString("FeatureNameUseGoogleDraco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use level category 的本地化字符串。
        /// </summary>
        internal static string FeatureNameUseLevelCategory {
            get {
                return ResourceManager.GetString("FeatureNameUseLevelCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use level(nw) category 的本地化字符串。
        /// </summary>
        internal static string FeatureNameUseNwLevelCategory {
            get {
                return ResourceManager.GetString("FeatureNameUseNwLevelCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use view&apos;s override color 的本地化字符串。
        /// </summary>
        internal static string FeatureNameUseViewOverrideGraphic {
            get {
                return ResourceManager.GetString("FeatureNameUseViewOverrideGraphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wireframe Mode 的本地化字符串。
        /// </summary>
        internal static string FeatureNameWireframe {
            get {
                return ResourceManager.GetString("FeatureNameWireframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The &apos;Home Folder&apos; of the Engine SDK is invalid and some features are disabled, Are you sure you want to continue? 的本地化字符串。
        /// </summary>
        internal static string HomeFolderIsInvalid {
            get {
                return ResourceManager.GetString("HomeFolderIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid format 的本地化字符串。
        /// </summary>
        internal static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launch {0} Fail! Error: {1} 的本地化字符串。
        /// </summary>
        internal static string LaunchAppFail {
            get {
                return ResourceManager.GetString("LaunchAppFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t find 3D View! 的本地化字符串。
        /// </summary>
        internal static string MessageCanNotFind3DView {
            get {
                return ResourceManager.GetString("MessageCanNotFind3DView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t find target path! 的本地化字符串。
        /// </summary>
        internal static string MessageCanNotFindTargetPath {
            get {
                return ResourceManager.GetString("MessageCanNotFindTargetPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export finish...Cancel {0} 的本地化字符串。
        /// </summary>
        internal static string MessageExportFinishCancel {
            get {
                return ResourceManager.GetString("MessageExportFinishCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export finish...Fail {0} 的本地化字符串。
        /// </summary>
        internal static string MessageExportFinishFail {
            get {
                return ResourceManager.GetString("MessageExportFinishFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export finish...Success 的本地化字符串。
        /// </summary>
        internal static string MessageExportFinishSuccess {
            get {
                return ResourceManager.GetString("MessageExportFinishSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exporting ... 的本地化字符串。
        /// </summary>
        internal static string MessageExporting {
            get {
                return ResourceManager.GetString("MessageExporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export success!(Elapsed: {0}) 的本地化字符串。
        /// </summary>
        internal static string MessageExportSuccess {
            get {
                return ResourceManager.GetString("MessageExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File save failure: {0} 的本地化字符串。
        /// </summary>
        internal static string MessageFileSaveFailure {
            get {
                return ResourceManager.GetString("MessageFileSaveFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alpha Mode 的本地化字符串。
        /// </summary>
        internal static string MessageLicenseAlphaMode {
            get {
                return ResourceManager.GetString("MessageLicenseAlphaMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Beta Mode 的本地化字符串。
        /// </summary>
        internal static string MessageLicenseBetaMode {
            get {
                return ResourceManager.GetString("MessageLicenseBetaMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expire: {0:yyyy-MM-dd} 的本地化字符串。
        /// </summary>
        internal static string MessageLicenseExpireBy {
            get {
                return ResourceManager.GetString("MessageLicenseExpireBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Free Edition 的本地化字符串。
        /// </summary>
        internal static string MessageLicenseFreeEdition {
            get {
                return ResourceManager.GetString("MessageLicenseFreeEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid license! 的本地化字符串。
        /// </summary>
        internal static string MessageLicenseInvalid {
            get {
                return ResourceManager.GetString("MessageLicenseInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 License invalid or expired! 的本地化字符串。
        /// </summary>
        internal static string MessageLicenseInvalidOrExpired {
            get {
                return ResourceManager.GetString("MessageLicenseInvalidOrExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total {0} days, {1} days used, remain {2} days 的本地化字符串。
        /// </summary>
        internal static string MessageLicenseTrialByDays {
            get {
                return ResourceManager.GetString("MessageLicenseTrialByDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total {0} minutes, {1} minutes used, remain {2} minutes 的本地化字符串。
        /// </summary>
        internal static string MessageLicenseTrialByMinutes {
            get {
                return ResourceManager.GetString("MessageLicenseTrialByMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total {0} times, {1} times used, remain {2} times 的本地化字符串。
        /// </summary>
        internal static string MessageLicenseTrialByTimes {
            get {
                return ResourceManager.GetString("MessageLicenseTrialByTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trial Edition 的本地化字符串。
        /// </summary>
        internal static string MessageLicenseTrialEdition {
            get {
                return ResourceManager.GetString("MessageLicenseTrialEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load export routine... 的本地化字符串。
        /// </summary>
        internal static string MessageLoadExportRoutine {
            get {
                return ResourceManager.GetString("MessageLoadExportRoutine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load export routine... Fail!!! 的本地化字符串。
        /// </summary>
        internal static string MessageLoadExportRoutineFail {
            get {
                return ResourceManager.GetString("MessageLoadExportRoutineFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load export routine... Success! 的本地化字符串。
        /// </summary>
        internal static string MessageLoadExportRoutineSuccess {
            get {
                return ResourceManager.GetString("MessageLoadExportRoutineSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no associated application installed. 的本地化字符串。
        /// </summary>
        internal static string MessageNoAssociatedApplications {
            get {
                return ResourceManager.GetString("MessageNoAssociatedApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No stray items were detected! 的本地化字符串。
        /// </summary>
        internal static string MessageNoStrayItemsWereDetected {
            get {
                return ResourceManager.GetString("MessageNoStrayItemsWereDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please open 3D View first! 的本地化字符串。
        /// </summary>
        internal static string MessageOpen3DViewFirst {
            get {
                return ResourceManager.GetString("MessageOpen3DViewFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation failure, elapsed time: {0} 的本地化字符串。
        /// </summary>
        internal static string MessageOperationFailureAndElapsedTime {
            get {
                return ResourceManager.GetString("MessageOperationFailureAndElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The program has an internal error, please try again later! 的本地化字符串。
        /// </summary>
        internal static string MessageOperationFailureAndTryLater {
            get {
                return ResourceManager.GetString("MessageOperationFailureAndTryLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation success, elapsed time: {0} 的本地化字符串。
        /// </summary>
        internal static string MessageOperationSuccessAndElapsedTime {
            get {
                return ResourceManager.GetString("MessageOperationSuccessAndElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select output path first! 的本地化字符串。
        /// </summary>
        internal static string MessageSelectOutputPathFirst {
            get {
                return ResourceManager.GetString("MessageSelectOutputPathFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} stray items are automatically hidden! 的本地化字符串。
        /// </summary>
        internal static string MessageStrayItemsHaveBeenHidden {
            get {
                return ResourceManager.GetString("MessageStrayItemsHaveBeenHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch to default 3D view... Fail!!! 的本地化字符串。
        /// </summary>
        internal static string MessageSwitchToDefaultViewFail {
            get {
                return ResourceManager.GetString("MessageSwitchToDefaultViewFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch to default 3D view... 的本地化字符串。
        /// </summary>
        internal static string MessageSwitchToDefaultViewStart {
            get {
                return ResourceManager.GetString("MessageSwitchToDefaultViewStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch to default 3D view... Success! 的本地化字符串。
        /// </summary>
        internal static string MessageSwitchToDefaultViewSuccess {
            get {
                return ResourceManager.GetString("MessageSwitchToDefaultViewSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Internal Origin 的本地化字符串。
        /// </summary>
        internal static string OriginTypeInternal {
            get {
                return ResourceManager.GetString("OriginTypeInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Internal Origin (Orient: Project North) 的本地化字符串。
        /// </summary>
        internal static string OriginTypeInternalForRevit {
            get {
                return ResourceManager.GetString("OriginTypeInternalForRevit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The output path target file already exists. The export will overwrite the original file. Are you sure you want to continue? 的本地化字符串。
        /// </summary>
        internal static string OutputFileExistedWarning {
            get {
                return ResourceManager.GetString("OutputFileExistedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sorry, this feature is available only to paying subscribers. 的本地化字符串。
        /// </summary>
        internal static string PayingSubscribersOnly {
            get {
                return ResourceManager.GetString("PayingSubscribersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quick Preview 的本地化字符串。
        /// </summary>
        internal static string PreviewAppName {
            get {
                return ResourceManager.GetString("PreviewAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabling this feature will improve rendering performance for larger models, but may result in larger output data size. Are you sure you want to enable it? 的本地化字符串。
        /// </summary>
        internal static string RenderingPerformancePreferredConfirm {
            get {
                return ResourceManager.GetString("RenderingPerformancePreferredConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The scene is empty, no data to process! 的本地化字符串。
        /// </summary>
        internal static string SceneIsEmpty {
            get {
                return ResourceManager.GetString("SceneIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No models have been loaded! 的本地化字符串。
        /// </summary>
        internal static string SceneNoData {
            get {
                return ResourceManager.GetString("SceneNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected {0} Views ... 的本地化字符串。
        /// </summary>
        internal static string SelectedViews {
            get {
                return ResourceManager.GetString("SelectedViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Views ... 的本地化字符串。
        /// </summary>
        internal static string SelectViews {
            get {
                return ResourceManager.GetString("SelectViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Site location invalid! 的本地化字符串。
        /// </summary>
        internal static string SiteLocationInvalid {
            get {
                return ResourceManager.GetString("SiteLocationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to cancel the current task? 的本地化字符串。
        /// </summary>
        internal static string SureToCancelTask {
            get {
                return ResourceManager.GetString("SureToCancelTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto 的本地化字符串。
        /// </summary>
        internal static string TextAuto {
            get {
                return ResourceManager.GetString("TextAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        internal static string TextDefault {
            get {
                return ResourceManager.GetString("TextDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Highest 的本地化字符串。
        /// </summary>
        internal static string TextHighest {
            get {
                return ResourceManager.GetString("TextHighest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lowest 的本地化字符串。
        /// </summary>
        internal static string TextLowest {
            get {
                return ResourceManager.GetString("TextLowest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal 的本地化字符串。
        /// </summary>
        internal static string TextNormal {
            get {
                return ResourceManager.GetString("TextNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Original Data 的本地化字符串。
        /// </summary>
        internal static string TextOriginal {
            get {
                return ResourceManager.GetString("TextOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Engine Logs 的本地化字符串。
        /// </summary>
        internal static string ToolsetCheckEngineLogs {
            get {
                return ResourceManager.GetString("ToolsetCheckEngineLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Revit Journals 的本地化字符串。
        /// </summary>
        internal static string ToolsetCheckRevitJournals {
            get {
                return ResourceManager.GetString("ToolsetCheckRevitJournals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Crate Projected Coordinate System Definition 的本地化字符串。
        /// </summary>
        internal static string ToolsetCreateProj {
            get {
                return ResourceManager.GetString("ToolsetCreateProj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically hides stray items 的本地化字符串。
        /// </summary>
        internal static string ToolsetHideStrayItems {
            get {
                return ResourceManager.GetString("ToolsetHideStrayItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pick a position 的本地化字符串。
        /// </summary>
        internal static string ToolsetPickPosition {
            get {
                return ResourceManager.GetString("ToolsetPickPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get position on a map 的本地化字符串。
        /// </summary>
        internal static string ToolsetPickPositionFromMap {
            get {
                return ResourceManager.GetString("ToolsetPickPositionFromMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please pick a position. 的本地化字符串。
        /// </summary>
        internal static string ToolsetPickPositionPrompt {
            get {
                return ResourceManager.GetString("ToolsetPickPositionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updated Revit.ini to solve stuck while exporting drawings 的本地化字符串。
        /// </summary>
        internal static string ToolsetUpdateRevitIni {
            get {
                return ResourceManager.GetString("ToolsetUpdateRevitIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string ToolTextAbout {
            get {
                return ResourceManager.GetString("ToolTextAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export to 3D Tiles 的本地化字符串。
        /// </summary>
        internal static string ToolTextExportToCesium3DTiles {
            get {
                return ResourceManager.GetString("ToolTextExportToCesium3DTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export to glTF/glb 的本地化字符串。
        /// </summary>
        internal static string ToolTextExportToGltf {
            get {
                return ResourceManager.GetString("ToolTextExportToGltf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export to SVFZIP 的本地化字符串。
        /// </summary>
        internal static string ToolTextExportToSvfzip {
            get {
                return ResourceManager.GetString("ToolTextExportToSvfzip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toolset 的本地化字符串。
        /// </summary>
        internal static string ToolTextToolset {
            get {
                return ResourceManager.GetString("ToolTextToolset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export the current 3D view to 3D Tiles format (for Cesium). 的本地化字符串。
        /// </summary>
        internal static string ToolTipExportToCesium3DTiles {
            get {
                return ResourceManager.GetString("ToolTipExportToCesium3DTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export the current 3D view to glTF/glb format. 的本地化字符串。
        /// </summary>
        internal static string ToolTipExportToGltf {
            get {
                return ResourceManager.GetString("ToolTipExportToGltf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export the current 3D view to SVFZIP format. 的本地化字符串。
        /// </summary>
        internal static string ToolTipExportToSvfzip {
            get {
                return ResourceManager.GetString("ToolTipExportToSvfzip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto 的本地化字符串。
        /// </summary>
        internal static string VisualStyleAuto {
            get {
                return ResourceManager.GetString("VisualStyleAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Colored 的本地化字符串。
        /// </summary>
        internal static string VisualStyleColored {
            get {
                return ResourceManager.GetString("VisualStyleColored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gray 的本地化字符串。
        /// </summary>
        internal static string VisualStyleGray {
            get {
                return ResourceManager.GetString("VisualStyleGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Realistic 的本地化字符串。
        /// </summary>
        internal static string VisualStyleRealistic {
            get {
                return ResourceManager.GetString("VisualStyleRealistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Textured 的本地化字符串。
        /// </summary>
        internal static string VisualStyleTextured {
            get {
                return ResourceManager.GetString("VisualStyleTextured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wireframe 的本地化字符串。
        /// </summary>
        internal static string VisualStyleWireframe {
            get {
                return ResourceManager.GetString("VisualStyleWireframe", resourceCulture);
            }
        }
    }
}
