//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bimangle.ForgeEngine.Dwg.App {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bimangle.ForgeEngine.Dwg.App.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 所有文件|*.* 的本地化字符串。
        /// </summary>
        internal static string DialogFilterAllFile {
            get {
                return ResourceManager.GetString("DialogFilterAllFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 授权文件|*.lic 的本地化字符串。
        /// </summary>
        internal static string DialogFilterLicenseFile {
            get {
                return ResourceManager.GetString("DialogFilterLicenseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轻量化模型文件|*.svfzip 的本地化字符串。
        /// </summary>
        internal static string DialogFilterSvfzip {
            get {
                return ResourceManager.GetString("DialogFilterSvfzip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载试用授权文件 的本地化字符串。
        /// </summary>
        internal static string DialogTitleLoadLicense {
            get {
                return ResourceManager.GetString("DialogTitleLoadLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出文件到 的本地化字符串。
        /// </summary>
        internal static string DialogTitleSelectTarget {
            get {
                return ResourceManager.GetString("DialogTitleSelectTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (试验功能)将每个部件中的构件融合为一个构件 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionConsolidateAssembly {
            get {
                return ResourceManager.GetString("FeatureDescriptionConsolidateAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将每个模型组中的构件融合为一个构件 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionConsolidateGroup {
            get {
                return ResourceManager.GetString("FeatureDescriptionConsolidateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不导出线状几何实体, 可提高导出及浏览性能。 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionExcludeLines {
            get {
                return ResourceManager.GetString("FeatureDescriptionExcludeLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不导出点状几何实体, 可提高导出及浏览性能。 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionExcludePoints {
            get {
                return ResourceManager.GetString("FeatureDescriptionExcludePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 适用于不关心构件属性的场景, 可提高导出及浏览性能。 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionExcludeProperties {
            get {
                return ResourceManager.GetString("FeatureDescriptionExcludeProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 适用于对构件美观度要求不高的场景, 可提高导出及浏览性能。 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionExcludeTexture {
            get {
                return ResourceManager.GetString("FeatureDescriptionExcludeTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (试验功能)导出所有的二维视图 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionExport2DViewAll {
            get {
                return ResourceManager.GetString("FeatureDescriptionExport2DViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (试验功能)转换输出图纸类型的二维视图 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionExport2DViewOnlySheet {
            get {
                return ResourceManager.GetString("FeatureDescriptionExport2DViewOnlySheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在输出的模型上叠加轴网信息。 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionExportGrids {
            get {
                return ResourceManager.GetString("FeatureDescriptionExportGrids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出图纸为2D图纸 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionExportMode2D {
            get {
                return ResourceManager.GetString("FeatureDescriptionExportMode2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出图纸为3D模型 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionExportMode3D {
            get {
                return ResourceManager.GetString("FeatureDescriptionExportMode3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出图纸为2D图纸和3D模型 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionExportModeAll {
            get {
                return ResourceManager.GetString("FeatureDescriptionExportModeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在输出的模型上叠加房间信息。 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionExportRooms {
            get {
                return ResourceManager.GetString("FeatureDescriptionExportRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用于定制开发, 文件名 elements_[data|props].json。 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionGenerateElementData {
            get {
                return ResourceManager.GetString("FeatureDescriptionGenerateElementData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成 SQLite 格式的模型属性数据库文件 model.sdb 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionGenerateModelsDb {
            get {
                return ResourceManager.GetString("FeatureDescriptionGenerateModelsDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成规格为 400x400,200x200,100x100 的缩略图片 (thumb{nnn}.png)  的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionGenerateThumbnail {
            get {
                return ResourceManager.GetString("FeatureDescriptionGenerateThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (试验功能)使用灰模表达三维几何实体 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionGray {
            get {
                return ResourceManager.GetString("FeatureDescriptionGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出结果包括默认不可见的图层 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionIncludeInvisibleLayers {
            get {
                return ResourceManager.GetString("FeatureDescriptionIncludeInvisibleLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出结果包括布局（导出为2D图纸） 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionIncludeLayouts {
            get {
                return ResourceManager.GetString("FeatureDescriptionIncludeLayouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 适用于只关注视图中部分构件的场景。 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionOnlySelected {
            get {
                return ResourceManager.GetString("FeatureDescriptionOnlySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (试验功能)分楼层组织模型树(按构件包围盒分层) 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionUseBoundLevelCategory {
            get {
                return ResourceManager.GetString("FeatureDescriptionUseBoundLevelCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (试验功能)使用当前视角作为轻量化模型默认视角 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionUseCurrentViewport {
            get {
                return ResourceManager.GetString("FeatureDescriptionUseCurrentViewport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分楼层组织模型树 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionUseLevelCategory {
            get {
                return ResourceManager.GetString("FeatureDescriptionUseLevelCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (试验功能)分楼层组织模型树(按 Navisworks 的分层标准) 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionUseNwLevelCategory {
            get {
                return ResourceManager.GetString("FeatureDescriptionUseNwLevelCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (试验功能)使用视图配色代替默认配色(如过滤器填充颜色等) 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionUseViewOverrideGraphic {
            get {
                return ResourceManager.GetString("FeatureDescriptionUseViewOverrideGraphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (试验功能)使用线框表达三维几何实体 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionWireframe {
            get {
                return ResourceManager.GetString("FeatureDescriptionWireframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 融合部件 的本地化字符串。
        /// </summary>
        internal static string FeatureNameConsolidateAssembly {
            get {
                return ResourceManager.GetString("FeatureNameConsolidateAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 融合模型组 的本地化字符串。
        /// </summary>
        internal static string FeatureNameConsolidateGroup {
            get {
                return ResourceManager.GetString("FeatureNameConsolidateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不输出模型线 的本地化字符串。
        /// </summary>
        internal static string FeatureNameExcludeLines {
            get {
                return ResourceManager.GetString("FeatureNameExcludeLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不输出模型点 的本地化字符串。
        /// </summary>
        internal static string FeatureNameExcludePoints {
            get {
                return ResourceManager.GetString("FeatureNameExcludePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不输出属性信息 的本地化字符串。
        /// </summary>
        internal static string FeatureNameExcludeProperties {
            get {
                return ResourceManager.GetString("FeatureNameExcludeProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不输出纹理图片 的本地化字符串。
        /// </summary>
        internal static string FeatureNameExcludeTexture {
            get {
                return ResourceManager.GetString("FeatureNameExcludeTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出二维视图(全部) 的本地化字符串。
        /// </summary>
        internal static string FeatureNameExport2DViewAll {
            get {
                return ResourceManager.GetString("FeatureNameExport2DViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出二维视图(仅图纸) 的本地化字符串。
        /// </summary>
        internal static string FeatureNameExport2DViewOnlySheet {
            get {
                return ResourceManager.GetString("FeatureNameExport2DViewOnlySheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模式 - 2D图纸和3D模型 的本地化字符串。
        /// </summary>
        internal static string FeatureNameExportExportModeAll {
            get {
                return ResourceManager.GetString("FeatureNameExportExportModeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出轴网 的本地化字符串。
        /// </summary>
        internal static string FeatureNameExportGrids {
            get {
                return ResourceManager.GetString("FeatureNameExportGrids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模式 - 2D图纸 的本地化字符串。
        /// </summary>
        internal static string FeatureNameExportMode2D {
            get {
                return ResourceManager.GetString("FeatureNameExportMode2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模式 - 3D模型 的本地化字符串。
        /// </summary>
        internal static string FeatureNameExportMode3D {
            get {
                return ResourceManager.GetString("FeatureNameExportMode3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出房间 的本地化字符串。
        /// </summary>
        internal static string FeatureNameExportRooms {
            get {
                return ResourceManager.GetString("FeatureNameExportRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出构件关联数据 的本地化字符串。
        /// </summary>
        internal static string FeatureNameGenerateElementData {
            get {
                return ResourceManager.GetString("FeatureNameGenerateElementData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成属性数据文件(model.sdb) 的本地化字符串。
        /// </summary>
        internal static string FeatureNameGenerateModelsDb {
            get {
                return ResourceManager.GetString("FeatureNameGenerateModelsDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成缩略图 的本地化字符串。
        /// </summary>
        internal static string FeatureNameGenerateThumbnail {
            get {
                return ResourceManager.GetString("FeatureNameGenerateThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 灰模模式 的本地化字符串。
        /// </summary>
        internal static string FeatureNameGray {
            get {
                return ResourceManager.GetString("FeatureNameGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包括不可见图层 的本地化字符串。
        /// </summary>
        internal static string FeatureNameIncludeInvisibleLayers {
            get {
                return ResourceManager.GetString("FeatureNameIncludeInvisibleLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出结果包括布局 的本地化字符串。
        /// </summary>
        internal static string FeatureNameIncludeLayouts {
            get {
                return ResourceManager.GetString("FeatureNameIncludeLayouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只导出选中的构件 的本地化字符串。
        /// </summary>
        internal static string FeatureNameOnlySelected {
            get {
                return ResourceManager.GetString("FeatureNameOnlySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模型树按楼层(包围盒)分组 的本地化字符串。
        /// </summary>
        internal static string FeatureNameUseBoundLevelCategory {
            get {
                return ResourceManager.GetString("FeatureNameUseBoundLevelCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用当前视角 的本地化字符串。
        /// </summary>
        internal static string FeatureNameUseCurrentViewport {
            get {
                return ResourceManager.GetString("FeatureNameUseCurrentViewport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模型树按楼层分组 的本地化字符串。
        /// </summary>
        internal static string FeatureNameUseLevelCategory {
            get {
                return ResourceManager.GetString("FeatureNameUseLevelCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模型树按楼层(Navisworks)分组 的本地化字符串。
        /// </summary>
        internal static string FeatureNameUseNwLevelCategory {
            get {
                return ResourceManager.GetString("FeatureNameUseNwLevelCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用视图配色 的本地化字符串。
        /// </summary>
        internal static string FeatureNameUseViewOverrideGraphic {
            get {
                return ResourceManager.GetString("FeatureNameUseViewOverrideGraphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线框模式 的本地化字符串。
        /// </summary>
        internal static string FeatureNameWireframe {
            get {
                return ResourceManager.GetString("FeatureNameWireframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法找到待转换的 3D 视图! 的本地化字符串。
        /// </summary>
        internal static string MessageCanNotFind3DView {
            get {
                return ResourceManager.GetString("MessageCanNotFind3DView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法获取输出文件位置! 的本地化字符串。
        /// </summary>
        internal static string MessageCanNotFindTargetPath {
            get {
                return ResourceManager.GetString("MessageCanNotFindTargetPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换输出结束...取消 {0} 的本地化字符串。
        /// </summary>
        internal static string MessageExportFinishCancel {
            get {
                return ResourceManager.GetString("MessageExportFinishCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换输出结束...失败 {0} 的本地化字符串。
        /// </summary>
        internal static string MessageExportFinishFail {
            get {
                return ResourceManager.GetString("MessageExportFinishFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在执行轻量化转换... 的本地化字符串。
        /// </summary>
        internal static string MessageExporting {
            get {
                return ResourceManager.GetString("MessageExporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轻量化文件转换成功!(耗时: {0}) 的本地化字符串。
        /// </summary>
        internal static string MessageExportSuccess {
            get {
                return ResourceManager.GetString("MessageExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件保存失败: {0} 的本地化字符串。
        /// </summary>
        internal static string MessageFileSaveFailure {
            get {
                return ResourceManager.GetString("MessageFileSaveFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alpha 测试模式 的本地化字符串。
        /// </summary>
        internal static string MessageLicenseAlphaMode {
            get {
                return ResourceManager.GetString("MessageLicenseAlphaMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Beta 测试模式 的本地化字符串。
        /// </summary>
        internal static string MessageLicenseBetaMode {
            get {
                return ResourceManager.GetString("MessageLicenseBetaMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效期至 {0:yyyy-MM-dd} 的本地化字符串。
        /// </summary>
        internal static string MessageLicenseExpireBy {
            get {
                return ResourceManager.GetString("MessageLicenseExpireBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 免费授权 的本地化字符串。
        /// </summary>
        internal static string MessageLicenseFreeEdition {
            get {
                return ResourceManager.GetString("MessageLicenseFreeEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 授权无效! 的本地化字符串。
        /// </summary>
        internal static string MessageLicenseInvalid {
            get {
                return ResourceManager.GetString("MessageLicenseInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无授权信息或授权已过期! 的本地化字符串。
        /// </summary>
        internal static string MessageLicenseInvalidOrExpired {
            get {
                return ResourceManager.GetString("MessageLicenseInvalidOrExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共可用 {0} 天, 已用 {1} 天, 剩余 {2} 天 的本地化字符串。
        /// </summary>
        internal static string MessageLicenseTrialByDays {
            get {
                return ResourceManager.GetString("MessageLicenseTrialByDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共可用 {0} 分钟, 已用 {1} 分钟, 剩余 {2} 分钟 的本地化字符串。
        /// </summary>
        internal static string MessageLicenseTrialByMinutes {
            get {
                return ResourceManager.GetString("MessageLicenseTrialByMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共可用 {0} 次, 已用 {1} 次, 剩余 {2} 次 的本地化字符串。
        /// </summary>
        internal static string MessageLicenseTrialByTimes {
            get {
                return ResourceManager.GetString("MessageLicenseTrialByTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 试用授权 的本地化字符串。
        /// </summary>
        internal static string MessageLicenseTrialEdition {
            get {
                return ResourceManager.GetString("MessageLicenseTrialEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动启动导出插件... 的本地化字符串。
        /// </summary>
        internal static string MessageLoadExportRoutine {
            get {
                return ResourceManager.GetString("MessageLoadExportRoutine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动启动导出插件...失败!!! 的本地化字符串。
        /// </summary>
        internal static string MessageLoadExportRoutineFail {
            get {
                return ResourceManager.GetString("MessageLoadExportRoutineFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动启动导出插件...成功! 的本地化字符串。
        /// </summary>
        internal static string MessageLoadExportRoutineSuccess {
            get {
                return ResourceManager.GetString("MessageLoadExportRoutineSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未安装关联应用程序 的本地化字符串。
        /// </summary>
        internal static string MessageNoAssociatedApplications {
            get {
                return ResourceManager.GetString("MessageNoAssociatedApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先切换至 3D 视图! 的本地化字符串。
        /// </summary>
        internal static string MessageOpen3DViewFirst {
            get {
                return ResourceManager.GetString("MessageOpen3DViewFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败, 总耗时: {0} 的本地化字符串。
        /// </summary>
        internal static string MessageOperationFailureAndElapsedTime {
            get {
                return ResourceManager.GetString("MessageOperationFailureAndElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序发生内部错误, 请稍后重试! 的本地化字符串。
        /// </summary>
        internal static string MessageOperationFailureAndTryLater {
            get {
                return ResourceManager.GetString("MessageOperationFailureAndTryLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作成功, 总耗时: {0} 的本地化字符串。
        /// </summary>
        internal static string MessageOperationSuccessAndElapsedTime {
            get {
                return ResourceManager.GetString("MessageOperationSuccessAndElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择输出路径! 的本地化字符串。
        /// </summary>
        internal static string MessageSelectOutputPathFirst {
            get {
                return ResourceManager.GetString("MessageSelectOutputPathFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动切换到默认视图...失败!!! 的本地化字符串。
        /// </summary>
        internal static string MessageSwitchToDefaultViewFail {
            get {
                return ResourceManager.GetString("MessageSwitchToDefaultViewFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动切换到默认视图... 的本地化字符串。
        /// </summary>
        internal static string MessageSwitchToDefaultViewStart {
            get {
                return ResourceManager.GetString("MessageSwitchToDefaultViewStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动切换到默认视图...成功! 的本地化字符串。
        /// </summary>
        internal static string MessageSwitchToDefaultViewSuccess {
            get {
                return ResourceManager.GetString("MessageSwitchToDefaultViewSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动 的本地化字符串。
        /// </summary>
        internal static string TextAuto {
            get {
                return ResourceManager.GetString("TextAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认 的本地化字符串。
        /// </summary>
        internal static string TextDefault {
            get {
                return ResourceManager.GetString("TextDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最高 的本地化字符串。
        /// </summary>
        internal static string TextHighest {
            get {
                return ResourceManager.GetString("TextHighest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最低 的本地化字符串。
        /// </summary>
        internal static string TextLowest {
            get {
                return ResourceManager.GetString("TextLowest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常 的本地化字符串。
        /// </summary>
        internal static string TextNormal {
            get {
                return ResourceManager.GetString("TextNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换输出结束...成功 的本地化字符串。
        /// </summary>
        internal static string tFinishSuccess {
            get {
                return ResourceManager.GetString("tFinishSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出为 SVFZIP 的本地化字符串。
        /// </summary>
        internal static string ToolTextExportToSvfzip {
            get {
                return ResourceManager.GetString("ToolTextExportToSvfzip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将当前三维视图显示的模型导出为 SVFZIP 轻量化格式。 的本地化字符串。
        /// </summary>
        internal static string ToolTipExportToSvfzip {
            get {
                return ResourceManager.GetString("ToolTipExportToSvfzip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 着色 的本地化字符串。
        /// </summary>
        internal static string VisualStyleColored {
            get {
                return ResourceManager.GetString("VisualStyleColored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 灰模 的本地化字符串。
        /// </summary>
        internal static string VisualStyleGray {
            get {
                return ResourceManager.GetString("VisualStyleGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 真实 的本地化字符串。
        /// </summary>
        internal static string VisualStyleRealistic {
            get {
                return ResourceManager.GetString("VisualStyleRealistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纹理 的本地化字符串。
        /// </summary>
        internal static string VisualStyleTextured {
            get {
                return ResourceManager.GetString("VisualStyleTextured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线框 的本地化字符串。
        /// </summary>
        internal static string VisualStyleWireframe {
            get {
                return ResourceManager.GetString("VisualStyleWireframe", resourceCulture);
            }
        }
    }
}
