//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bimangle.ForgeEngine.Georeferncing {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WpfGeoreferncingRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WpfGeoreferncingRes() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bimangle.ForgeEngine.Georeferncing.WpfGeoreferncingRes", typeof(WpfGeoreferncingRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 _Cancel 的本地化字符串。
        /// </summary>
        public static string btnCancel_Text {
            get {
                return ResourceManager.GetString("btnCancel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string btnEdit_Text {
            get {
                return ResourceManager.GetString("btnEdit.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _OK 的本地化字符串。
        /// </summary>
        public static string btnOK_Text {
            get {
                return ResourceManager.GetString("btnOK.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string btnProjCoordinateOffsetSave_Text {
            get {
                return ResourceManager.GetString("btnProjCoordinateOffsetSave.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save conversion setting as model&apos;s default settings 的本地化字符串。
        /// </summary>
        public static string btnProjCoordinateOffsetSave_ToolTip {
            get {
                return ResourceManager.GetString("btnProjCoordinateOffsetSave.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string btnProjDefinitionSave_Text {
            get {
                return ResourceManager.GetString("btnProjDefinitionSave.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save projected definition as model&apos;s projected definition 的本地化字符串。
        /// </summary>
        public static string btnProjDefinitionSave_ToolTip {
            get {
                return ResourceManager.GetString("btnProjDefinitionSave.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Reset 的本地化字符串。
        /// </summary>
        public static string btnReset_Text {
            get {
                return ResourceManager.GetString("btnReset.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Test 的本地化字符串。
        /// </summary>
        public static string btnTest_Text {
            get {
                return ResourceManager.GetString("btnTest.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use the center of the site plan 的本地化字符串。
        /// </summary>
        public static string cbEnuAlignOriginToSitePlaneCenter_Text {
            get {
                return ResourceManager.GetString("cbEnuAlignOriginToSitePlaneCenter.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatic alignment to ground curvature 的本地化字符串。
        /// </summary>
        public static string cbEnuAutoAlignToGround_Text {
            get {
                return ResourceManager.GetString("cbEnuAutoAlignToGround.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use the default coordinate of the site 的本地化字符串。
        /// </summary>
        public static string cbEnuUseProjectLocation_Text {
            get {
                return ResourceManager.GetString("cbEnuUseProjectLocation.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use the center of the site plan 的本地化字符串。
        /// </summary>
        public static string cbLocalAlignOriginToSitePlaneCenter_Text {
            get {
                return ResourceManager.GetString("cbLocalAlignOriginToSitePlaneCenter.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use the default coordinate of the site 的本地化字符串。
        /// </summary>
        public static string cbLocalUseProjectLocation_Text {
            get {
                return ResourceManager.GetString("cbLocalUseProjectLocation.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model Coordinate System: 的本地化字符串。
        /// </summary>
        public static string lblAutoOriginLocation_Text {
            get {
                return ResourceManager.GetString("lblAutoOriginLocation.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced Options: 的本地化字符串。
        /// </summary>
        public static string lblEnuAdvanced_Text {
            get {
                return ResourceManager.GetString("lblEnuAdvanced.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Height: 的本地化字符串。
        /// </summary>
        public static string lblEnuHeight_Text {
            get {
                return ResourceManager.GetString("lblEnuHeight.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Latitude: 的本地化字符串。
        /// </summary>
        public static string lblEnuLatitude_Text {
            get {
                return ResourceManager.GetString("lblEnuLatitude.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Longitude: 的本地化字符串。
        /// </summary>
        public static string lblEnuLongitude_Text {
            get {
                return ResourceManager.GetString("lblEnuLongitude.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Origin Model Coordinate (unit: metre): 的本地化字符串。
        /// </summary>
        public static string lblEnuModelOriginCoordinate_Text {
            get {
                return ResourceManager.GetString("lblEnuModelOriginCoordinate.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E(X): 的本地化字符串。
        /// </summary>
        public static string lblEnuModelOriginE_Text {
            get {
                return ResourceManager.GetString("lblEnuModelOriginE.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 H(Z): 的本地化字符串。
        /// </summary>
        public static string lblEnuModelOriginH_Text {
            get {
                return ResourceManager.GetString("lblEnuModelOriginH.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 N(Y): 的本地化字符串。
        /// </summary>
        public static string lblEnuModelOriginN_Text {
            get {
                return ResourceManager.GetString("lblEnuModelOriginN.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Origin Geographic Coordinate: 的本地化字符串。
        /// </summary>
        public static string lblEnuOriginCoordinate_Text {
            get {
                return ResourceManager.GetString("lblEnuOriginCoordinate.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model Coordinate System: 的本地化字符串。
        /// </summary>
        public static string lblEnuOriginLocation_Text {
            get {
                return ResourceManager.GetString("lblEnuOriginLocation.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rotation: 的本地化字符串。
        /// </summary>
        public static string lblEnuRotation_Text {
            get {
                return ResourceManager.GetString("lblEnuRotation.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Constant offset: 的本地化字符串。
        /// </summary>
        public static string lblGeoidConstantOffset_Text {
            get {
                return ResourceManager.GetString("lblGeoidConstantOffset.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Geoid Height Correction: 的本地化字符串。
        /// </summary>
        public static string lblGeoidHeightCorrection_Text {
            get {
                return ResourceManager.GetString("lblGeoidHeightCorrection.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Height: 的本地化字符串。
        /// </summary>
        public static string lblLocalHeight_Text {
            get {
                return ResourceManager.GetString("lblLocalHeight.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Latitude: 的本地化字符串。
        /// </summary>
        public static string lblLocalLatitude_Text {
            get {
                return ResourceManager.GetString("lblLocalLatitude.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Longitude: 的本地化字符串。
        /// </summary>
        public static string lblLocalLongitude_Text {
            get {
                return ResourceManager.GetString("lblLocalLongitude.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Origin Model Coordinate (unit: metre): 的本地化字符串。
        /// </summary>
        public static string lblLocalModelOriginCoordinate_Text {
            get {
                return ResourceManager.GetString("lblLocalModelOriginCoordinate.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E(X): 的本地化字符串。
        /// </summary>
        public static string lblLocalModelOriginE_Text {
            get {
                return ResourceManager.GetString("lblLocalModelOriginE.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 H(Z): 的本地化字符串。
        /// </summary>
        public static string lblLocalModelOriginH_Text {
            get {
                return ResourceManager.GetString("lblLocalModelOriginH.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 N(Y): 的本地化字符串。
        /// </summary>
        public static string lblLocalModelOriginN_Text {
            get {
                return ResourceManager.GetString("lblLocalModelOriginN.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Origin Geographic Coordinate (default): 的本地化字符串。
        /// </summary>
        public static string lblLocalOriginCoordinate_Text {
            get {
                return ResourceManager.GetString("lblLocalOriginCoordinate.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model Coordinate System: 的本地化字符串。
        /// </summary>
        public static string lblLocalOriginLocation_Text {
            get {
                return ResourceManager.GetString("lblLocalOriginLocation.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rotation: 的本地化字符串。
        /// </summary>
        public static string lblLocalRotation_Text {
            get {
                return ResourceManager.GetString("lblLocalRotation.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Planar Coordinate Conversion: 的本地化字符串。
        /// </summary>
        public static string lblProjCoordinateOffset_Text {
            get {
                return ResourceManager.GetString("lblProjCoordinateOffset.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Projected Coordinate System: 的本地化字符串。
        /// </summary>
        public static string lblProjDefinition_Text {
            get {
                return ResourceManager.GetString("lblProjDefinition.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Projection Height: 的本地化字符串。
        /// </summary>
        public static string lblProjectionHeight_Text {
            get {
                return ResourceManager.GetString("lblProjectionHeight.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model Coordinate System: 的本地化字符串。
        /// </summary>
        public static string lblProjOriginLocation_Text {
            get {
                return ResourceManager.GetString("lblProjOriginLocation.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto 的本地化字符串。
        /// </summary>
        public static string tabPageAuto_Text {
            get {
                return ResourceManager.GetString("tabPageAuto.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ENU 的本地化字符串。
        /// </summary>
        public static string tabPageEnu_Text {
            get {
                return ResourceManager.GetString("tabPageEnu.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local 的本地化字符串。
        /// </summary>
        public static string tabPageLocal_Text {
            get {
                return ResourceManager.GetString("tabPageLocal.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Projected 的本地化字符串。
        /// </summary>
        public static string tabPageProj_Text {
            get {
                return ResourceManager.GetString("tabPageProj.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Georeferncing 的本地化字符串。
        /// </summary>
        public static string this_Text {
            get {
                return ResourceManager.GetString("this.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 metre 的本地化字符串。
        /// </summary>
        public static string txtEnuHeight_ToolTip {
            get {
                return ResourceManager.GetString("txtEnuHeight.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Degree, range: -90.0 to 90.0 的本地化字符串。
        /// </summary>
        public static string txtEnuLatitude_ToolTip {
            get {
                return ResourceManager.GetString("txtEnuLatitude.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Degree, range: -180.0 to 180.0 的本地化字符串。
        /// </summary>
        public static string txtEnuLongitude_ToolTip {
            get {
                return ResourceManager.GetString("txtEnuLongitude.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 metre 的本地化字符串。
        /// </summary>
        public static string txtEnuModelOriginE_ToolTip {
            get {
                return ResourceManager.GetString("txtEnuModelOriginE.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 metre 的本地化字符串。
        /// </summary>
        public static string txtEnuModelOriginH_ToolTip {
            get {
                return ResourceManager.GetString("txtEnuModelOriginH.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 metre 的本地化字符串。
        /// </summary>
        public static string txtEnuModelOriginN_ToolTip {
            get {
                return ResourceManager.GetString("txtEnuModelOriginN.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Degree, range: -360.0 to 360.0 的本地化字符串。
        /// </summary>
        public static string txtEnuRotation_ToolTip {
            get {
                return ResourceManager.GetString("txtEnuRotation.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 metre 的本地化字符串。
        /// </summary>
        public static string txtGeoidConstantOffset_ToolTip {
            get {
                return ResourceManager.GetString("txtGeoidConstantOffset.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 metre 的本地化字符串。
        /// </summary>
        public static string txtLocalHeight_ToolTip {
            get {
                return ResourceManager.GetString("txtLocalHeight.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Degree, range: -90.0 to 90.0 的本地化字符串。
        /// </summary>
        public static string txtLocalLatitude_ToolTip {
            get {
                return ResourceManager.GetString("txtLocalLatitude.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Degree, range: -180.0 to 180.0 的本地化字符串。
        /// </summary>
        public static string txtLocalLongitude_ToolTip {
            get {
                return ResourceManager.GetString("txtLocalLongitude.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 metre 的本地化字符串。
        /// </summary>
        public static string txtLocalModelOriginE_ToolTip {
            get {
                return ResourceManager.GetString("txtLocalModelOriginE.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 metre 的本地化字符串。
        /// </summary>
        public static string txtLocalModelOriginH_ToolTip {
            get {
                return ResourceManager.GetString("txtLocalModelOriginH.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 metre 的本地化字符串。
        /// </summary>
        public static string txtLocalModelOriginN_ToolTip {
            get {
                return ResourceManager.GetString("txtLocalModelOriginN.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Degree, range: -360.0 to 360.0 的本地化字符串。
        /// </summary>
        public static string txtLocalRotation_ToolTip {
            get {
                return ResourceManager.GetString("txtLocalRotation.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 metre 的本地化字符串。
        /// </summary>
        public static string txtProjectionHeight_ToolTip {
            get {
                return ResourceManager.GetString("txtProjectionHeight.ToolTip", resourceCulture);
            }
        }
    }
}
