//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bimangle.ForgeEngine.Georeferncing {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WpfGeoreferncingTestRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WpfGeoreferncingTestRes() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bimangle.ForgeEngine.Georeferncing.WpfGeoreferncingTestRes", typeof(WpfGeoreferncingTestRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Swap NE 的本地化字符串。
        /// </summary>
        public static string btnSwapNE_Text {
            get {
                return ResourceManager.GetString("btnSwapNE_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Test 的本地化字符串。
        /// </summary>
        public static string btnTestRun_Text {
            get {
                return ResourceManager.GetString("btnTestRun_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Projected Parameters 的本地化字符串。
        /// </summary>
        public static string gpProjParameters_Text {
            get {
                return ResourceManager.GetString("gpProjParameters_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test Run 的本地化字符串。
        /// </summary>
        public static string gpTestRun_Text {
            get {
                return ResourceManager.GetString("gpTestRun_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Constant offset: 的本地化字符串。
        /// </summary>
        public static string lblGeoidConstantOffset_Text {
            get {
                return ResourceManager.GetString("lblGeoidConstantOffset_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Geoid Height: 的本地化字符串。
        /// </summary>
        public static string lblGeoidHeight_Text {
            get {
                return ResourceManager.GetString("lblGeoidHeight_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Geoid Height Correction: 的本地化字符串。
        /// </summary>
        public static string lblGeoidHeightCorrection_Text {
            get {
                return ResourceManager.GetString("lblGeoidHeightCorrection_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model: 的本地化字符串。
        /// </summary>
        public static string lblModel_Text {
            get {
                return ResourceManager.GetString("lblModel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E(X) (m): 的本地化字符串。
        /// </summary>
        public static string lblModelE_Text {
            get {
                return ResourceManager.GetString("lblModelE_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 H(Z) (m): 的本地化字符串。
        /// </summary>
        public static string lblModelH_Text {
            get {
                return ResourceManager.GetString("lblModelH_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 N(Y) (m): 的本地化字符串。
        /// </summary>
        public static string lblModelN_Text {
            get {
                return ResourceManager.GetString("lblModelN_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Planar Coordinate Conversion: 的本地化字符串。
        /// </summary>
        public static string lblProjCoordinateOffset_Text {
            get {
                return ResourceManager.GetString("lblProjCoordinateOffset_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Projected Coordinate System: 的本地化字符串。
        /// </summary>
        public static string lblProjDefinition_Text {
            get {
                return ResourceManager.GetString("lblProjDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Projected: 的本地化字符串。
        /// </summary>
        public static string lblProjected_Text {
            get {
                return ResourceManager.GetString("lblProjected_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E (m): 的本地化字符串。
        /// </summary>
        public static string lblProjectedE_Text {
            get {
                return ResourceManager.GetString("lblProjectedE_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 H (m): 的本地化字符串。
        /// </summary>
        public static string lblProjectedH_Text {
            get {
                return ResourceManager.GetString("lblProjectedH_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 N (m): 的本地化字符串。
        /// </summary>
        public static string lblProjectedN_Text {
            get {
                return ResourceManager.GetString("lblProjectedN_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Projection Height: 的本地化字符串。
        /// </summary>
        public static string lblProjectionHeight_Text {
            get {
                return ResourceManager.GetString("lblProjectionHeight_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 World (WGS 84): 的本地化字符串。
        /// </summary>
        public static string lblWorld_Text {
            get {
                return ResourceManager.GetString("lblWorld_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Height (m): 的本地化字符串。
        /// </summary>
        public static string lblWorldHeight_Text {
            get {
                return ResourceManager.GetString("lblWorldHeight_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Latitude (degree): 的本地化字符串。
        /// </summary>
        public static string lblWorldLat_Text {
            get {
                return ResourceManager.GetString("lblWorldLat_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Longitude (degree): 的本地化字符串。
        /// </summary>
        public static string lblWorldLon_Text {
            get {
                return ResourceManager.GetString("lblWorldLon_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Georeferncing Test Run 的本地化字符串。
        /// </summary>
        public static string this_Text {
            get {
                return ResourceManager.GetString("this_Text", resourceCulture);
            }
        }
    }
}
