//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bimangle.ForgeEngine.Georeferncing {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WpfProjCreateRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WpfProjCreateRes() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bimangle.ForgeEngine.Georeferncing.WpfProjCreateRes", typeof(WpfProjCreateRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Calc By Reference Point 的本地化字符串。
        /// </summary>
        public static string btnCalc_Text {
            get {
                return ResourceManager.GetString("btnCalc_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Cancel 的本地化字符串。
        /// </summary>
        public static string btnCancel_Text {
            get {
                return ResourceManager.GetString("btnCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Generate Definition 的本地化字符串。
        /// </summary>
        public static string btnGenerate_Text {
            get {
                return ResourceManager.GetString("btnGenerate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _OK 的本地化字符串。
        /// </summary>
        public static string btnOK_Text {
            get {
                return ResourceManager.GetString("btnOK_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pinned 的本地化字符串。
        /// </summary>
        public static string cbPinned_Text {
            get {
                return ResourceManager.GetString("cbPinned_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Definition 的本地化字符串。
        /// </summary>
        public static string gpDefinition_Text {
            get {
                return ResourceManager.GetString("gpDefinition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter 的本地化字符串。
        /// </summary>
        public static string gpParameter_Text {
            get {
                return ResourceManager.GetString("gpParameter_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Central Meridian: 的本地化字符串。
        /// </summary>
        public static string lblCentralMeridian_Text {
            get {
                return ResourceManager.GetString("lblCentralMeridian_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 False Easting: 的本地化字符串。
        /// </summary>
        public static string lblFalseEasting_Text {
            get {
                return ResourceManager.GetString("lblFalseEasting_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 False Northing: 的本地化字符串。
        /// </summary>
        public static string lblFalseNorthing_Text {
            get {
                return ResourceManager.GetString("lblFalseNorthing_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Geographic Coordinate System: 的本地化字符串。
        /// </summary>
        public static string lblGcs_Text {
            get {
                return ResourceManager.GetString("lblGcs_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Projected Coordinate System Definition 的本地化字符串。
        /// </summary>
        public static string this_Text {
            get {
                return ResourceManager.GetString("this_Text", resourceCulture);
            }
        }
    }
}
