//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bimangle.ForgeEngine.Georeferncing {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WpfProjParamCalcRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WpfProjParamCalcRes() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bimangle.ForgeEngine.Georeferncing.WpfProjParamCalcRes", typeof(WpfProjParamCalcRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 _Cancel 的本地化字符串。
        /// </summary>
        public static string btnCancel_Text {
            get {
                return ResourceManager.GetString("btnCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _OK 的本地化字符串。
        /// </summary>
        public static string btnOK_Text {
            get {
                return ResourceManager.GetString("btnOK_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get position on a map 的本地化字符串。
        /// </summary>
        public static string btnPickPosition_Text {
            get {
                return ResourceManager.GetString("btnPickPosition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get position on model 的本地化字符串。
        /// </summary>
        public static string btnPickPositionOnModel_Text {
            get {
                return ResourceManager.GetString("btnPickPositionOnModel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reference Point Geographic Coordinates: 的本地化字符串。
        /// </summary>
        public static string lblRefPointGeoCoords_Text {
            get {
                return ResourceManager.GetString("lblRefPointGeoCoords_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Latitude: 的本地化字符串。
        /// </summary>
        public static string lblRefPointGeoLat_Text {
            get {
                return ResourceManager.GetString("lblRefPointGeoLat_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Longitude: 的本地化字符串。
        /// </summary>
        public static string lblRefPointGeoLon_Text {
            get {
                return ResourceManager.GetString("lblRefPointGeoLon_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reference Point Model Plane Coordinates: 的本地化字符串。
        /// </summary>
        public static string lblRefPointLocalCoords_Text {
            get {
                return ResourceManager.GetString("lblRefPointLocalCoords_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E(X): 的本地化字符串。
        /// </summary>
        public static string lblRefPointLocalX_Text {
            get {
                return ResourceManager.GetString("lblRefPointLocalX_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 N(Y): 的本地化字符串。
        /// </summary>
        public static string lblRefPointLocalY_Text {
            get {
                return ResourceManager.GetString("lblRefPointLocalY_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Calc By Reference Point 的本地化字符串。
        /// </summary>
        public static string this_Text {
            get {
                return ResourceManager.GetString("this_Text", resourceCulture);
            }
        }
    }
}
