//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bimangle.ForgeEngine.Revit {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bimangle.ForgeEngine.Revit.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 All Files|*.* 的本地化字符串。
        /// </summary>
        internal static string DialogFilterAllFile {
            get {
                return ResourceManager.GetString("DialogFilterAllFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 License File|*.lic 的本地化字符串。
        /// </summary>
        internal static string DialogFilterLicenseFile {
            get {
                return ResourceManager.GetString("DialogFilterLicenseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WebGL Model|*.svfzip 的本地化字符串。
        /// </summary>
        internal static string DialogFilterSvfzip {
            get {
                return ResourceManager.GetString("DialogFilterSvfzip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load license file 的本地化字符串。
        /// </summary>
        internal static string DialogTitleLoadLicense {
            get {
                return ResourceManager.GetString("DialogTitleLoadLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse target file 的本地化字符串。
        /// </summary>
        internal static string DialogTitleSelectTarget {
            get {
                return ResourceManager.GetString("DialogTitleSelectTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Consolidate assembly&apos;s members to one node  的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionConsolidateAssembly {
            get {
                return ResourceManager.GetString("FeatureDescriptionConsolidateAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Consolidate model group&apos;s members to one node 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionConsolidateGroup {
            get {
                return ResourceManager.GetString("FeatureDescriptionConsolidateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionExcludeLines {
            get {
                return ResourceManager.GetString("FeatureDescriptionExcludeLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionExcludePoints {
            get {
                return ResourceManager.GetString("FeatureDescriptionExcludePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionExcludeProperties {
            get {
                return ResourceManager.GetString("FeatureDescriptionExcludeProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionExcludeTexture {
            get {
                return ResourceManager.GetString("FeatureDescriptionExcludeTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionExportGrids {
            get {
                return ResourceManager.GetString("FeatureDescriptionExportGrids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionExportRooms {
            get {
                return ResourceManager.GetString("FeatureDescriptionExportRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filename: elements_[data|props].json 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionGenerateElementData {
            get {
                return ResourceManager.GetString("FeatureDescriptionGenerateElementData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate model properties database file (SQLite) 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionGenerateModelsDb {
            get {
                return ResourceManager.GetString("FeatureDescriptionGenerateModelsDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate 400x400,200x200,100x100 thumbnail image (thumb{nnn}.png)  的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionGenerateThumbnail {
            get {
                return ResourceManager.GetString("FeatureDescriptionGenerateThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionOnlySelected {
            get {
                return ResourceManager.GetString("FeatureDescriptionOnlySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use level category by element&apos;s bounding box 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionUseBoundLevelCategory {
            get {
                return ResourceManager.GetString("FeatureDescriptionUseBoundLevelCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use current 3d view camera viewport 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionUseCurrentViewport {
            get {
                return ResourceManager.GetString("FeatureDescriptionUseCurrentViewport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionUseLevelCategory {
            get {
                return ResourceManager.GetString("FeatureDescriptionUseLevelCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use level category like Navisworks 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionUseNwLevelCategory {
            get {
                return ResourceManager.GetString("FeatureDescriptionUseNwLevelCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use current view&apos;s override graphic color 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionUseViewOverrideGraphic {
            get {
                return ResourceManager.GetString("FeatureDescriptionUseViewOverrideGraphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wireframe Mode 的本地化字符串。
        /// </summary>
        internal static string FeatureDescriptionWireframe {
            get {
                return ResourceManager.GetString("FeatureDescriptionWireframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Consolidate assembly 的本地化字符串。
        /// </summary>
        internal static string FeatureNameConsolidateAssembly {
            get {
                return ResourceManager.GetString("FeatureNameConsolidateAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Consolidate model group 的本地化字符串。
        /// </summary>
        internal static string FeatureNameConsolidateGroup {
            get {
                return ResourceManager.GetString("FeatureNameConsolidateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exclude geometry lines 的本地化字符串。
        /// </summary>
        internal static string FeatureNameExcludeLines {
            get {
                return ResourceManager.GetString("FeatureNameExcludeLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exclude geometry points 的本地化字符串。
        /// </summary>
        internal static string FeatureNameExcludePoints {
            get {
                return ResourceManager.GetString("FeatureNameExcludePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exclude properties data 的本地化字符串。
        /// </summary>
        internal static string FeatureNameExcludeProperties {
            get {
                return ResourceManager.GetString("FeatureNameExcludeProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exclude material texture images 的本地化字符串。
        /// </summary>
        internal static string FeatureNameExcludeTexture {
            get {
                return ResourceManager.GetString("FeatureNameExcludeTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export grids 的本地化字符串。
        /// </summary>
        internal static string FeatureNameExportGrids {
            get {
                return ResourceManager.GetString("FeatureNameExportGrids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export rooms 的本地化字符串。
        /// </summary>
        internal static string FeatureNameExportRooms {
            get {
                return ResourceManager.GetString("FeatureNameExportRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate elements data 的本地化字符串。
        /// </summary>
        internal static string FeatureNameGenerateElementData {
            get {
                return ResourceManager.GetString("FeatureNameGenerateElementData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate model.sdb 的本地化字符串。
        /// </summary>
        internal static string FeatureNameGenerateModelsDb {
            get {
                return ResourceManager.GetString("FeatureNameGenerateModelsDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate thumbnail 的本地化字符串。
        /// </summary>
        internal static string FeatureNameGenerateThumbnail {
            get {
                return ResourceManager.GetString("FeatureNameGenerateThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export selected elements only 的本地化字符串。
        /// </summary>
        internal static string FeatureNameOnlySelected {
            get {
                return ResourceManager.GetString("FeatureNameOnlySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use level(bound) category 的本地化字符串。
        /// </summary>
        internal static string FeatureNameUseBoundLevelCategory {
            get {
                return ResourceManager.GetString("FeatureNameUseBoundLevelCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use current viewport 的本地化字符串。
        /// </summary>
        internal static string FeatureNameUseCurrentViewport {
            get {
                return ResourceManager.GetString("FeatureNameUseCurrentViewport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use level category 的本地化字符串。
        /// </summary>
        internal static string FeatureNameUseLevelCategory {
            get {
                return ResourceManager.GetString("FeatureNameUseLevelCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use level(nw) category 的本地化字符串。
        /// </summary>
        internal static string FeatureNameUseNwLevelCategory {
            get {
                return ResourceManager.GetString("FeatureNameUseNwLevelCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use view&apos;s override color 的本地化字符串。
        /// </summary>
        internal static string FeatureNameUseViewOverrideGraphic {
            get {
                return ResourceManager.GetString("FeatureNameUseViewOverrideGraphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wireframe Mode 的本地化字符串。
        /// </summary>
        internal static string FeatureNameWireframe {
            get {
                return ResourceManager.GetString("FeatureNameWireframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t find 3D View! 的本地化字符串。
        /// </summary>
        internal static string MessageCanNotFind3DView {
            get {
                return ResourceManager.GetString("MessageCanNotFind3DView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t find target path! 的本地化字符串。
        /// </summary>
        internal static string MessageCanNotFindTargetPath {
            get {
                return ResourceManager.GetString("MessageCanNotFindTargetPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export finish...Cancel {0} 的本地化字符串。
        /// </summary>
        internal static string MessageExportFinishCancel {
            get {
                return ResourceManager.GetString("MessageExportFinishCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export finish...Fail {0} 的本地化字符串。
        /// </summary>
        internal static string MessageExportFinishFail {
            get {
                return ResourceManager.GetString("MessageExportFinishFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export finish...Success 的本地化字符串。
        /// </summary>
        internal static string MessageExportFinishSuccess {
            get {
                return ResourceManager.GetString("MessageExportFinishSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exporting ... 的本地化字符串。
        /// </summary>
        internal static string MessageExporting {
            get {
                return ResourceManager.GetString("MessageExporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export success!(Elapsed: {0}) 的本地化字符串。
        /// </summary>
        internal static string MessageExportSuccess {
            get {
                return ResourceManager.GetString("MessageExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File save failure: {0} 的本地化字符串。
        /// </summary>
        internal static string MessageFileSaveFailure {
            get {
                return ResourceManager.GetString("MessageFileSaveFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alpha Mode 的本地化字符串。
        /// </summary>
        internal static string MessageLicenseAlphaMode {
            get {
                return ResourceManager.GetString("MessageLicenseAlphaMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Beta Mode 的本地化字符串。
        /// </summary>
        internal static string MessageLicenseBetaMode {
            get {
                return ResourceManager.GetString("MessageLicenseBetaMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expire: {0:yyyy-MM-dd} 的本地化字符串。
        /// </summary>
        internal static string MessageLicenseExpireBy {
            get {
                return ResourceManager.GetString("MessageLicenseExpireBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Free Edition 的本地化字符串。
        /// </summary>
        internal static string MessageLicenseFreeEdition {
            get {
                return ResourceManager.GetString("MessageLicenseFreeEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid license! 的本地化字符串。
        /// </summary>
        internal static string MessageLicenseInvalid {
            get {
                return ResourceManager.GetString("MessageLicenseInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 License invalid or expired! 的本地化字符串。
        /// </summary>
        internal static string MessageLicenseInvalidOrExpired {
            get {
                return ResourceManager.GetString("MessageLicenseInvalidOrExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total {0} days, {1} days used, remain {2} days 的本地化字符串。
        /// </summary>
        internal static string MessageLicenseTrialByDays {
            get {
                return ResourceManager.GetString("MessageLicenseTrialByDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total {0} minutes, {1} minutes used, remain {2} minutes 的本地化字符串。
        /// </summary>
        internal static string MessageLicenseTrialByMinutes {
            get {
                return ResourceManager.GetString("MessageLicenseTrialByMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total {0} times, {1} times used, remain {2} times 的本地化字符串。
        /// </summary>
        internal static string MessageLicenseTrialByTimes {
            get {
                return ResourceManager.GetString("MessageLicenseTrialByTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trial Edition 的本地化字符串。
        /// </summary>
        internal static string MessageLicenseTrialEdition {
            get {
                return ResourceManager.GetString("MessageLicenseTrialEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load export rountine... 的本地化字符串。
        /// </summary>
        internal static string MessageLoadExportRoutine {
            get {
                return ResourceManager.GetString("MessageLoadExportRoutine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load export rountine... Fail!!! 的本地化字符串。
        /// </summary>
        internal static string MessageLoadExportRoutineFail {
            get {
                return ResourceManager.GetString("MessageLoadExportRoutineFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load export rountine... Success! 的本地化字符串。
        /// </summary>
        internal static string MessageLoadExportRoutineSuccess {
            get {
                return ResourceManager.GetString("MessageLoadExportRoutineSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no associated application installed. 的本地化字符串。
        /// </summary>
        internal static string MessageNoAssociatedApplications {
            get {
                return ResourceManager.GetString("MessageNoAssociatedApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please open 3D View first! 的本地化字符串。
        /// </summary>
        internal static string MessageOpen3DViewFirst {
            get {
                return ResourceManager.GetString("MessageOpen3DViewFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation failure, elapsed time: {0} 的本地化字符串。
        /// </summary>
        internal static string MessageOperationFailureAndElapsedTime {
            get {
                return ResourceManager.GetString("MessageOperationFailureAndElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The program has an internal error, please try again later! 的本地化字符串。
        /// </summary>
        internal static string MessageOperationFailureAndTryLater {
            get {
                return ResourceManager.GetString("MessageOperationFailureAndTryLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation success, elapsed time: {0} 的本地化字符串。
        /// </summary>
        internal static string MessageOperationSuccessAndElapsedTime {
            get {
                return ResourceManager.GetString("MessageOperationSuccessAndElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select output path first! 的本地化字符串。
        /// </summary>
        internal static string MessageSelectOutputPathFirst {
            get {
                return ResourceManager.GetString("MessageSelectOutputPathFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch to default 3D view... Fail!!! 的本地化字符串。
        /// </summary>
        internal static string MessageSwitchToDefaultViewFail {
            get {
                return ResourceManager.GetString("MessageSwitchToDefaultViewFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch to default 3D view... 的本地化字符串。
        /// </summary>
        internal static string MessageSwitchToDefaultViewStart {
            get {
                return ResourceManager.GetString("MessageSwitchToDefaultViewStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch to default 3D view... Success! 的本地化字符串。
        /// </summary>
        internal static string MessageSwitchToDefaultViewSuccess {
            get {
                return ResourceManager.GetString("MessageSwitchToDefaultViewSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export to SVFZIP 的本地化字符串。
        /// </summary>
        internal static string ToolTextExportToSvfzip {
            get {
                return ResourceManager.GetString("ToolTextExportToSvfzip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export the current 3D view to SVFZIP format. 的本地化字符串。
        /// </summary>
        internal static string ToolTipExportToSvfzip {
            get {
                return ResourceManager.GetString("ToolTipExportToSvfzip", resourceCulture);
            }
        }
    }
}
