//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bimangle.ForgeEngine.Georeferncing {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GeoStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeoStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bimangle.ForgeEngine.Georeferncing.GeoStrings", typeof(GeoStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Align origin to site plane center 的本地化字符串。
        /// </summary>
        internal static string AlignOriginToSitePlaneCenter {
            get {
                return ResourceManager.GetString("AlignOriginToSitePlaneCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatic alignment to ground 的本地化字符串。
        /// </summary>
        internal static string AutoAlignToGround {
            get {
                return ResourceManager.GetString("AutoAlignToGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Auto) 的本地化字符串。
        /// </summary>
        internal static string AutoMode {
            get {
                return ResourceManager.GetString("AutoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target file already exists.  overwrite it? 的本地化字符串。
        /// </summary>
        internal static string ConfirmOverwriteFile {
            get {
                return ResourceManager.GetString("ConfirmOverwriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Really want to save the current coordinate offset as the model default? 的本地化字符串。
        /// </summary>
        internal static string ConfirmSaveOffsets {
            get {
                return ResourceManager.GetString("ConfirmSaveOffsets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Really want to save the current projected definition as the model default? 的本地化字符串。
        /// </summary>
        internal static string ConfirmSaveProjDefinition {
            get {
                return ResourceManager.GetString("ConfirmSaveProjDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Coordinate Offset 的本地化字符串。
        /// </summary>
        internal static string CoordinateOffset {
            get {
                return ResourceManager.GetString("CoordinateOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Definition Source 的本地化字符串。
        /// </summary>
        internal static string DefinitionSource {
            get {
                return ResourceManager.GetString("DefinitionSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load From ... 的本地化字符串。
        /// </summary>
        internal static string DefinitionSourceBrowse {
            get {
                return ResourceManager.GetString("DefinitionSourceBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create ... 的本地化字符串。
        /// </summary>
        internal static string DefinitionSourceCreate {
            get {
                return ResourceManager.GetString("DefinitionSourceCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom 的本地化字符串。
        /// </summary>
        internal static string DefinitionSourceCustom {
            get {
                return ResourceManager.GetString("DefinitionSourceCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proejct Internal 的本地化字符串。
        /// </summary>
        internal static string DefinitionSourceEmbed {
            get {
                return ResourceManager.GetString("DefinitionSourceEmbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project Default 的本地化字符串。
        /// </summary>
        internal static string DefinitionSourceProjectDefault {
            get {
                return ResourceManager.GetString("DefinitionSourceProjectDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project Folder 的本地化字符串。
        /// </summary>
        internal static string DefinitionSourceProjectFolder {
            get {
                return ResourceManager.GetString("DefinitionSourceProjectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recently 的本地化字符串。
        /// </summary>
        internal static string DefinitionSourceRecently {
            get {
                return ResourceManager.GetString("DefinitionSourceRecently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid height value 的本地化字符串。
        /// </summary>
        internal static string ErrorMessageHeight {
            get {
                return ResourceManager.GetString("ErrorMessageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid latitude value (Ranges: -90.0 to 90.0) 的本地化字符串。
        /// </summary>
        internal static string ErrorMessageLatitude {
            get {
                return ResourceManager.GetString("ErrorMessageLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Longitude value (Ranges: -180.0 to 180.0) 的本地化字符串。
        /// </summary>
        internal static string ErrorMessageLongitude {
            get {
                return ResourceManager.GetString("ErrorMessageLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid number 的本地化字符串。
        /// </summary>
        internal static string ErrorMessageNumber {
            get {
                return ResourceManager.GetString("ErrorMessageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid rotation value (Ranges: -360.0 to 360.0) 的本地化字符串。
        /// </summary>
        internal static string ErrorMessageRotation {
            get {
                return ResourceManager.GetString("ErrorMessageRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Path 的本地化字符串。
        /// </summary>
        internal static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Beijing 1954 的本地化字符串。
        /// </summary>
        internal static string GcsBeijing1954 {
            get {
                return ResourceManager.GetString("GcsBeijing1954", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CSCS2000 的本地化字符串。
        /// </summary>
        internal static string GcsCGCS2000 {
            get {
                return ResourceManager.GetString("GcsCGCS2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WGS84 的本地化字符串。
        /// </summary>
        internal static string GcsWGS84 {
            get {
                return ResourceManager.GetString("GcsWGS84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Xian 1980 的本地化字符串。
        /// </summary>
        internal static string GcsXian1980 {
            get {
                return ResourceManager.GetString("GcsXian1980", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Georeferenced Method 的本地化字符串。
        /// </summary>
        internal static string GeoreferencedMode {
            get {
                return ResourceManager.GetString("GeoreferencedMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto 的本地化字符串。
        /// </summary>
        internal static string GeoreferencedModeAuto {
            get {
                return ResourceManager.GetString("GeoreferencedModeAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ENU 的本地化字符串。
        /// </summary>
        internal static string GeoreferencedModeEnu {
            get {
                return ResourceManager.GetString("GeoreferencedModeEnu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local 的本地化字符串。
        /// </summary>
        internal static string GeoreferencedModeLocal {
            get {
                return ResourceManager.GetString("GeoreferencedModeLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Projected 的本地化字符串。
        /// </summary>
        internal static string GeoreferencedModeProj {
            get {
                return ResourceManager.GetString("GeoreferencedModeProj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Data 的本地化字符串。
        /// </summary>
        internal static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Projected Defintion 的本地化字符串。
        /// </summary>
        internal static string InvalidProjectDefinition {
            get {
                return ResourceManager.GetString("InvalidProjectDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Origin Corrdinate 的本地化字符串。
        /// </summary>
        internal static string OriginCoordinate {
            get {
                return ResourceManager.GetString("OriginCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Origin Default Corrdinate 的本地化字符串。
        /// </summary>
        internal static string OriginDefaultCoordinate {
            get {
                return ResourceManager.GetString("OriginDefaultCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Origin Location 的本地化字符串。
        /// </summary>
        internal static string OriginLocation {
            get {
                return ResourceManager.GetString("OriginLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatic 的本地化字符串。
        /// </summary>
        internal static string OriginTypeAuto {
            get {
                return ResourceManager.GetString("OriginTypeAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Internal Origin (Orient: Project North) 的本地化字符串。
        /// </summary>
        internal static string OriginTypeInternal {
            get {
                return ResourceManager.GetString("OriginTypeInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project Base Point (Orient: Project North) 的本地化字符串。
        /// </summary>
        internal static string OriginTypeProject {
            get {
                return ResourceManager.GetString("OriginTypeProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shared Coordinate Origin (Orient: True North) 的本地化字符串。
        /// </summary>
        internal static string OriginTypeShared {
            get {
                return ResourceManager.GetString("OriginTypeShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Survey Point (Orient: True North) 的本地化字符串。
        /// </summary>
        internal static string OriginTypeSurvey {
            get {
                return ResourceManager.GetString("OriginTypeSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Projected Definition 的本地化字符串。
        /// </summary>
        internal static string ProjectedDefinition {
            get {
                return ResourceManager.GetString("ProjectedDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Projected Elevation 的本地化字符串。
        /// </summary>
        internal static string ProjElevation {
            get {
                return ResourceManager.GetString("ProjElevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 China 1956 Yellow Sea 的本地化字符串。
        /// </summary>
        internal static string ProjElevationChina1956YellowSea {
            get {
                return ResourceManager.GetString("ProjElevationChina1956YellowSea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 China 1985 National 的本地化字符串。
        /// </summary>
        internal static string ProjElevationChina1985National {
            get {
                return ResourceManager.GetString("ProjElevationChina1985National", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom 的本地化字符串。
        /// </summary>
        internal static string ProjElevationCustom {
            get {
                return ResourceManager.GetString("ProjElevationCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        internal static string ProjElevationDefault {
            get {
                return ResourceManager.GetString("ProjElevationDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save successfully! 的本地化字符串。
        /// </summary>
        internal static string SaveSuccessfully {
            get {
                return ResourceManager.GetString("SaveSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Crate Projected Coordinate System Definition 的本地化字符串。
        /// </summary>
        internal static string ToolsetCreateProj {
            get {
                return ResourceManager.GetString("ToolsetCreateProj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pick a position 的本地化字符串。
        /// </summary>
        internal static string ToolsetPickPosition {
            get {
                return ResourceManager.GetString("ToolsetPickPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get position on a map 的本地化字符串。
        /// </summary>
        internal static string ToolsetPickPositionFromMap {
            get {
                return ResourceManager.GetString("ToolsetPickPositionFromMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please pick a position. 的本地化字符串。
        /// </summary>
        internal static string ToolsetPickPositionPrompt {
            get {
                return ResourceManager.GetString("ToolsetPickPositionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Feet 的本地化字符串。
        /// </summary>
        internal static string UnitFeet {
            get {
                return ResourceManager.GetString("UnitFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Metre 的本地化字符串。
        /// </summary>
        internal static string UnitMetre {
            get {
                return ResourceManager.GetString("UnitMetre", resourceCulture);
            }
        }
    }
}
